# Generated by Django 5.2.9 on 2025-12-08 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=500)),
                ('long_description', models.TextField()),
                ('day_in_life', models.TextField(blank=True)),
                ('skills', models.JSONField(default=list, help_text='List of required skills')),
                ('salary_range_min', models.IntegerField(blank=True, null=True)),
                ('salary_range_max', models.IntegerField(blank=True, null=True)),
                ('demand_note', models.CharField(blank=True, max_length=200)),
                ('misconceptions', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list, help_text="List of tags e.g. ['tech', 'creative']")),
                ('seo_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('article', 'Article'), ('video', 'Video'), ('book', 'Book'), ('tool', 'Tool')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='careers.career')),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='careers.career')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_time', models.CharField(help_text="e.g. '2 weeks'", max_length=100)),
                ('resources', models.JSONField(blank=True, default=list, help_text='List of resource objects or links')),
                ('example_project', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='careers.roadmap')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.roadmapstep')),
            ],
        ),
    ]
